#!/usr/bin/env python3
"""Fix horizontally flipped (mirror) yaw labels using the direction detector's verdict.

Background: rows showing the back of the head with no visible face are exempt from
sixd validation (intent_fallback), so the generative model's left/right swaps slipped
through QA (confirmed in s005 after s007. 2026-09-08: the user spotted one image in
the teacher2 preview; the cross-check found 614 rows, and a 9/9 calibration confirmed
the detector side is correct). The direction in auto_qa.jsonl is the output of a
detector that looks at the actual image, so it serves as a clean signal independent
of the generation intent.

The direction convention is subject-side (the subject's own left/right):
  - yawpose yaw 0..180 (viewer-left = subject turned right) → right_* is correct
  - yawpose yaw 180..360 → left_* is correct
So within the decidable band (|signed(yaw)| 25°-155°), rows where the detector
reports the opposite side with high confidence are judged mirrored and yaw is
flipped to 360°-yaw. pitch is left unchanged.

The suspect list (qa_s00X_direction_suspects.json) is read from the file generated
and saved beforehand by the cross-check (audit trail). The reference yaw for the
decision is the current value in labels, not the snapshot in the list, which
prevents double flipping. The fix is applied to labels_fixed / train / val and
records the old value yaw_deg_orig_mirror, the detector info and label_fix (fully
reversible).

Usage:
    uv run python scripts/fix_mirror_by_direction.py \
        --suspects data/yawpitchpose/qa_s005_direction_suspects.json \
        --source synthetic_005 --prefix s005_
"""
import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", type=str, default=str(ROOT / "data" / "yawpitchpose"))
    ap.add_argument("--suspects", type=str, required=True,
                    help="suspect list json generated by the cross-check")
    ap.add_argument("--source", type=str, required=True,
                    help="target source name (e.g. synthetic_005)")
    ap.add_argument("--prefix", type=str, required=True,
                    help="image name prefix within the dataset (e.g. s005_)")
    ap.add_argument("--min-score", type=float, default=0.9,
                    help="suspect rows below this direction_score are not flipped")
    args = ap.parse_args()

    data = Path(args.data)
    tag = args.prefix.rstrip("_")
    suspects = json.load(open(args.suspects))
    target = {f"images/{args.prefix}{s['file']}": s for s in suspects
              if s["score"] >= args.min_score
              and not s.get("excluded_by_user")}
    excl = sum(1 for s in suspects if s.get("excluded_by_user"))
    low = len(suspects) - len(target) - excl
    print(f"suspects: {len(suspects)} (score>={args.min_score}: {len(target)}, "
          f"low-score skip: {low}, user-excluded: {excl})")

    stats: Counter = Counter()
    for name in ("labels_fixed", "train", "val"):
        path = data / f"{name}.jsonl"
        rows = [json.loads(l) for l in open(path)]
        changed = 0
        for r in rows:
            s = target.get(r["image"])
            if s is None or r["source"] != args.source:
                continue
            if "yaw_deg_orig_mirror" in r:      # idempotent: skip already applied
                continue
            r["yaw_deg_orig_mirror"] = r["yaw_deg"]
            r["yaw_deg"] = round((360.0 - r["yaw_deg"]) % 360.0, 4)
            r["detector_direction"] = s["direction"]
            r["detector_score"] = s["score"]
            r["label_fix"] = f"mirror_fix_{tag}_direction"
            changed += 1
        with open(path, "w") as f:
            for r in rows:
                f.write(json.dumps(r) + "\n")
        stats[name] = changed
        print(f"{name}.jsonl: {changed} rows flipped")

    summary = {
        "suspects": str(args.suspects),
        "criteria": {"basis": "auto_qa direction (subject-side) vs intent",
                     "signed_yaw_range": [25.0, 155.0],
                     "min_score": args.min_score},
        "flipped": dict(stats),
        "note": "only yaw is flipped to 360-yaw (pitch unchanged). Old value in "
                f"yaw_deg_orig_mirror, action recorded as label_fix=mirror_fix_{tag}_"
                "direction. split membership unchanged.",
    }
    out = data / f"{tag}_mirror_fix_summary.json"
    with open(out, "w") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
