#!/usr/bin/env python3
"""Fix the horizontally flipped (mirror) yaw labels of s007 using the oracle verdict.

Background: for s007 (deep pitch band) the automatic sixd validation does not work,
so the generative model's left/right swaps slipped through QA and got in (confirmed
by a 9/9 visual calibration). A yaw teacher that has never been trained on s007
(v6u) serves as the oracle, and only rows with clear mirror support get yaw flipped
to 360°-yaw. pitch is left unchanged.

Oracle verdict (mirror confirmed) requires:
  - |signed(yaw)| within 25°-155° (near frontal/back of the head is excluded since
    it cannot be told apart from a mirror)
  - circ(oracle, 360-yaw) <= 30° and circ(oracle, yaw) > 50°

The fix is applied to the matching rows of labels_fixed.jsonl / train.jsonl /
val.jsonl, recording for every target row the old value as yaw_deg_orig_mirror, the
oracle value as oracle_yaw and the action as label_fix="mirror_fix_v6u" (fully
reversible). split membership is not changed. The summary is saved to
s007_mirror_fix_summary.json.

Usage:
    uv run python scripts/fix_s007_mirror.py --data data/yawpitchpose

The oracle json (qa_s007_oracle.json: [{image, gt, pitch, oracle}, ...]) was
generated by inference in scripts with a teacher that has not seen s007. After
updating the teacher it can be regenerated and this script rerun (already-fixed rows
are idempotent via the presence of yaw_deg_orig_mirror).
"""
import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def signed(d: float) -> float:
    return ((d + 180.0) % 360.0) - 180.0


def circ(a: float, b: float) -> float:
    d = abs(a - b) % 360.0
    return min(d, 360.0 - d)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", type=str, default=str(ROOT / "data" / "yawpitchpose"))
    ap.add_argument("--oracle", type=str, default="",
                    help="oracle json (default: <data>/qa_s007_oracle.json)")
    ap.add_argument("--mirror-tol", type=float, default=30.0)
    ap.add_argument("--gt-min-gap", type=float, default=50.0)
    args = ap.parse_args()

    data = Path(args.data)
    oracle_path = Path(args.oracle) if args.oracle else data / "qa_s007_oracle.json"
    oracle = {r["image"]: r for r in json.load(open(oracle_path))}

    # Decide the mirror-confirmed rows. The reference yaw for the decision is the
    # current value in labels, not the snapshot in the oracle json (so that manual
    # fixes or rollbacks made after the json was generated are not double-flipped)
    current = {}
    for l in open(data / "labels_fixed.jsonl"):
        r = json.loads(l)
        current[r["image"]] = r
    flip: dict[str, float] = {}
    for img, r in oracle.items():
        cur = current.get(img)
        if cur is None:
            continue
        gt = float(cur["yaw_deg"]) % 360.0
        if not 25.0 <= abs(signed(gt)) <= 155.0:
            continue
        o = float(r["oracle"])
        if circ(o, (360.0 - gt) % 360.0) <= args.mirror_tol \
                and circ(o, gt) > args.gt_min_gap:
            flip[img] = o
    print(f"mirror-confirmed rows: {len(flip)}")

    stats: Counter = Counter()
    for name in ("labels_fixed", "train", "val"):
        path = data / f"{name}.jsonl"
        rows = [json.loads(l) for l in open(path)]
        changed = 0
        for r in rows:
            if r["image"] not in flip:
                continue
            if "yaw_deg_orig_mirror" in r:      # idempotent: skip already applied
                continue
            r["yaw_deg_orig_mirror"] = r["yaw_deg"]
            r["yaw_deg"] = round((360.0 - r["yaw_deg"]) % 360.0, 4)
            r["oracle_yaw"] = round(flip[r["image"]], 1)
            r["label_fix"] = "mirror_fix_v6u"
            changed += 1
        with open(path, "w") as f:
            for r in rows:
                f.write(json.dumps(r) + "\n")
        stats[name] = changed
        print(f"{name}.jsonl: {changed} rows flipped")

    summary = {
        "oracle": str(oracle_path),
        "criteria": {"signed_yaw_range": [25.0, 155.0],
                     "mirror_tol": args.mirror_tol,
                     "gt_min_gap": args.gt_min_gap},
        "flipped": dict(stats),
        "note": "only yaw is flipped to 360-yaw (pitch unchanged). Old value in "
                "yaw_deg_orig_mirror, action recorded as label_fix=mirror_fix_v6u. "
                "split membership unchanged.",
    }
    with open(data / "s007_mirror_fix_summary.json", "w") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
